//! High-level abstractions for running quantised small language models (SLMs) locally.
//!
//! The crate is structured as a stack of composable traits:
//!
//! * **Token layer** – [`SlmToken`], [`SlmVocab`]: encode/decode between strings and token IDs.
//! * **Hardware layer** – [`SlmContext`], [`SlmBatch`]: KV-cache management and batched decoding.
//! * **Model loading** – [`SlmModelConfig`], [`SlmModel`], [`SlmHfModel`]: load GGUF weights, optionally from HuggingFace.
//! * **Generation loop** – [`SlmInference`], [`SlmSimpleInference`]: prefill and autoregressive sampling.
//! * **Chat formatting** – [`SlmFormatter`], [`SlmDynamicFormatter`]: model-family chat templates.
//! * **Conversation layer** – [`SlmOracle`], [`SlmSimpleOracle`]: turn-taking, context save/restore, and JSON-guided generation.
//! * **Constrained decoding** – [`SlmConstraint`], [`SlmSimpleTokEnv`]: grammar-gated token sampling.

pub mod hf;
pub use hf::SlmHfModel;
mod answer;
pub mod core;
pub mod errors;
mod formatter;
pub mod inference;
pub mod models;
mod oracle;
mod simple_oracle;
mod llg_lark;

pub use answer::SlmAnswer;
use errors::*;
pub use formatter::SlmFormatter;
pub use inference::{SlmBoxedAction, SlmAction, SlmInference, SlmSimpleInference};
pub use models::SlmDynamicFormatter;
pub use oracle::{SlmOracle, SlmJsonOracle};
pub use simple_oracle::SlmSimpleOracle;
pub use llg_lark::SlmSimpleTokEnv;
use std::path::Path;
use std::result::Result;
use llguidance::toktrie;

/// A numeric token identifier produced and consumed by a model's vocabulary.
///
/// Implementors are typically thin newtypes over a `u32` or `i32`.
/// The `Copy` bound allows tokens to be stored cheaply in vectors and batches.
pub trait SlmToken: Copy {
    /// Returns the token ID as a signed 32-bit integer (the C FFI convention).
    fn as_i32(&self) -> i32;
    /// Constructs a token from a raw signed 32-bit ID.
    fn from_i32(i: i32) -> Self;
}

/// Identifies which participant in a conversation produced a given message.
///
/// Chat-template formatters use this to wrap messages in the correct
/// role-specific delimiters (e.g. `<|im_start|>user\n` for Qwen, `[INST]` for Mistral).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SlmRole {
    /// A privileged initial message that sets the model's persona and constraints.
    System,
    /// A message from the human side of the conversation.
    User,
    /// A message generated by the model.
    Assistant,
}

impl SlmRole {
    pub fn as_str(&self) -> &'static str {
        match self {
            SlmRole::System => "system",
            SlmRole::User => "user",
            SlmRole::Assistant => "assistant",
        }
    }
}

/// A position inside the KV cache, identifying a token slot and the parallel
/// sequence (fork) it belongs to.
///
/// `SlmPos` values are returned by [`SlmInference::save`] and consumed by
/// [`SlmInference::rollback`] to implement backtracking through the conversation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SlmPos {
    /// Zero-based index of the token slot within the sequence.
    pub token_pos: usize,
    /// Identifier of the parallel sequence this position belongs to.
    /// `0` is used for single-sequence (non-forked) inference.
    pub fork_id: usize,
}

#[allow(dead_code)]
impl SlmPos {
    fn fork_id(&self) -> usize {
        self.fork_id
    }
    fn token_pos(&self) -> usize {
        self.token_pos
    }
    pub fn new(token_pos: usize, fork_id: usize) -> SlmPos {
        Self { token_pos, fork_id }
    }
}

/// A submission buffer that accumulates tokens before they are decoded in bulk.
///
/// Batching amortises the cost of the model's forward pass: instead of invoking
/// the backend once per token, callers fill the batch and call [`SlmContext::decode`] once.
pub trait SlmBatch<Token: SlmToken> {
    /// Enqueue a single token at the given KV-cache position.
    ///
    /// Set `logits` to `true` for the last token in a prefill chunk, or for every
    /// token during generation, so that [`SlmContext::sample_with_constraint`] can
    /// read the computed logits.
    fn add(&mut self, token: Token, pos: SlmPos, logits: bool) -> Result<(), BatchError>;
    /// Discard all queued tokens, resetting the batch for re-use.
    fn clear(&mut self);
    /// Number of token slots currently queued in this batch.
    fn n_tokens(&self) -> usize;
    /// Maximum number of token slots this batch can hold.
    fn n_max(&self) -> usize;
}

/// Factory that describes how a specific model variant should be loaded.
///
/// Callers typically construct a concrete config (e.g. with builder methods),
/// then call [`load_gguf`](Self::load_gguf) to obtain a usable [`SlmModel`].
pub trait SlmModelConfig {
    type Context: SlmContext;
    type Model: SlmModel<Context = Self::Context>;
    /// Load model weights from the given GGUF file and return a model handle.
    fn load_gguf(self, path: impl AsRef<Path>) -> Result<Self::Model, GgufLoaderError>;
}

pub type SlmTokEnv = toktrie::TokEnv;

/// Vocabulary operations: encoding strings to tokens and decoding tokens to bytes.
///
/// A vocabulary is accessible through [`SlmContext::vocab`].  The method
/// signatures mirror the llama.cpp tokeniser API, and [`tok_env`](Self::tok_env)
/// exposes the underlying `TokEnv` required by the `llguidance` constrained
/// generation library.
pub trait SlmVocab {
    type Token: SlmToken;
    /// Total number of token IDs in the vocabulary (including special tokens).
    fn vocab_size(&self) -> usize;
    /// Convert a token to its raw byte representation.
    ///
    /// `special` – render special tokens as text instead of skipping them.  
    /// `left_strip` – if `Some(n)`, strip up to `n` leading space bytes from the result.
    fn token_to_bytes(
        &self,
        token: Self::Token,
        special: bool,
        left_strip: Option<usize>,
    ) -> Result<Vec<u8>, TokenToStringError>;
    /// Tokenise a UTF-8 string into a sequence of model token IDs.
    ///
    /// `add_special` – prepend/append BOS/EOS markers as required by the model.  
    /// `parse_special` – treat special-token text sequences (e.g. `<|im_start|>`) as
    /// their corresponding token IDs rather than plain text.
    fn str_to_tokens(
        &self,
        str: &str,
        add_special: bool,
        parse_special: bool,
    ) -> Result<Vec<Self::Token>, StringToTokenError>;
    /// Returns the llguidance token environment, needed for constrained generation.
    fn tok_env(&self) -> &SlmTokEnv;
}

/// A loaded model weight set from which inference contexts can be created.
///
/// The model itself is stateless; all mutable state (KV cache, sampler, etc.)
/// lives in the [`SlmContext`] produced by the builder returned from
/// [`context`](Self::context).
pub trait SlmModel {
    type Context: SlmContext;
    /// Return a builder for creating a new inference context backed by this model.
    fn context(&self) -> impl SlmContextBuilder<Self::Context>;
}

/// Quantization format used for KV-cache tensors.
///
/// Lower-precision formats reduce VRAM usage at the cost of a small accuracy
/// penalty.  `F16`/`F32` are lossless; the `Q*` variants trade precision for memory.
pub enum SlmKvType {
    /// 4-bit quantised KV cache.
    Q4,
    /// 5-bit quantised KV cache.
    Q5,
    /// 6-bit quantised KV cache.
    Q6,
    /// 8-bit quantised KV cache.
    Q8,
    /// Raw (non-llama.cpp-quantised) 8-bit KV cache.
    RawQ8,
    /// Half-precision (16-bit float) KV cache.
    F16,
    /// Single-precision (32-bit float) KV cache.
    F32,
}

/// Builder for configuring and instantiating an [`SlmContext`].
///
/// Obtained from [`SlmModel::context`].  All `with_*` methods consume `self`
/// and return `Self` for method chaining.  Call [`build`](Self::build) to
/// produce the configured context.
pub trait SlmContextBuilder<T> {
    /// Consume the builder and create the inference context.
    fn build(self) -> Result<T, ContextBuilderError>;
    /// Configure sampler parameters.
    ///
    /// `temperature` – softmax temperature (`0.0` → greedy, `1.0` → unmodified distribution).  
    /// `top_k` – keep only the top-k highest-probability candidates; `≤0` disables.  
    /// `top_p` – nucleus-sampling threshold `(0.0–1.0)`; `1.0` disables.
    fn with_sampler(self, temperature: f32, top_k: i32, top_p: f32) -> Self;
    /// Set the maximum context length in tokens.
    fn with_n_ctx(self, n_ctx: usize) -> Self;
    /// Override the quantization format for KV-cache key and value tensors.
    fn with_gen_type_kv(self, k: SlmKvType, v: SlmKvType) -> Self;
    /// Set the maximum batch size (tokens processed in a single forward pass).
    fn with_n_batch(self, n_batch: usize) -> Self;
    /// Enable or disable Flash Attention for this context.
    fn with_flash_attn(self, enable: bool) -> Self;
}

/// Declares which KV-cache editing operations an [`SlmContext`] implementation supports.
///
/// Used by [`SlmSimpleInference`] to select the most efficient rollback strategy.
/// Variants are ordered by capability: higher values include the capabilities of all
/// lower values.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, PartialOrd)]
pub enum SlmEditLevel {
    /// Only dump/restore is supported.  Every rollback requires a full
    /// serialise–deserialise round-trip via [`SlmContext::dump`] / [`SlmContext::restore`].
    #[default]
    DumpRestore = 0,
    /// [`SlmContext::truncate`] is available: the tail of the KV cache can be
    /// removed efficiently without a full dump/restore cycle.
    Cut = 1,
    /// Both [`SlmContext::truncate`] and [`SlmContext::cut`] are available:
    /// arbitrary token ranges can be excised from the KV cache in-place.
    Truncate = 2,
}

/// Instruction returned by a [`SlmConstraint`] after a sampled token is committed.
///
/// The generation loop in [`SlmSimpleInference`] inspects this value to decide
/// whether to run a normal forward pass, inject deterministic tokens, or halt.
#[derive(Debug, Clone)]
pub enum SlmConstraintStep {
    /// Skip the normal sampling step and inject this sequence of token IDs directly
    /// into the KV cache.  Used when the grammar uniquely determines the next tokens
    /// (e.g. forced punctuation in a JSON schema).
    FastForward(Vec<i32>),
    /// Run the normal forward pass for the next token.
    Forward,
    /// Terminate generation immediately; the constraint has been fully satisfied.
    Stop,
}

/// Token-level filter applied during autoregressive sampling.
///
/// Implementations can enforce structural constraints on model output, such as
/// JSON-schema validation ([`LarkConstraint`]) or simple token allow-lists.
///
/// The constraint is invoked once per generated token in two phases:
/// 1. [`mask`](Self::mask) adjusts logits *before* sampling.
/// 2. [`forward`](Self::forward) is called *after* sampling to advance the
///    constraint's internal state machine.
///
/// [`prefill`](Self::prefill) synchronises the constraint with text that was
/// already committed to the KV cache before generation begins.
pub trait SlmConstraint {
    /// Mask logits in-place by setting forbidden token logits to `f32::NEG_INFINITY`.
    ///
    /// Returns `true` to continue generation, or `false` to stop immediately.
    fn mask(&mut self, logits: &mut [f32]) -> Result<bool, SamplingError>;
    /// Advance the constraint's state machine after `token_id` was sampled.
    ///
    /// Returns a [`SlmConstraintStep`] telling the generation loop what to do next.
    fn forward(&mut self, token_id: i32) -> Result<SlmConstraintStep, SamplingError>;
    /// Synchronise the constraint state with `text` that is already present in the
    /// KV cache (e.g. a reasoning trigger prefix).
    fn prefill(&mut self, text: &str) -> Result<(), SamplingError>;
}

/// Core inference context that owns a KV cache and provides all token-level operations
/// required for autoregressive text generation.
///
/// A context is obtained from [`SlmContextBuilder::build`] and is used by inference
/// helpers such as [`SlmSimpleInference`].  Each context is associated with a single
/// model and maintains mutable state (KV cache, sampler state) across calls.
pub trait SlmContext {
    /// The token type produced and consumed by this context.
    type Token: SlmToken;
    /// The batch type used to submit tokens for decoding.
    type Batch: SlmBatch<Self::Token>;
    type Vocab: SlmVocab<Token = Self::Token>;
    /// Returns a reference to this context's vocabulary for token encoding/decoding.
    fn vocab(&self) -> &Self::Vocab;

    /// Allocates a new batch capable of holding up to `tokens` token slots across
    /// up to `sequences` parallel sequences.
    fn new_batch(&self, tokens: usize, sequences: usize) -> Result<Self::Batch, BatchError>;

    /// Returns the maximum number of token slots the context can process in a single
    /// [`decode`](Self::decode) call.
    fn max_batch_len(&self) -> usize;

    /// Runs the model forward pass for all tokens currently queued in `batch`,
    /// updating the KV cache and computing logits for every slot that requested them.
    fn decode(&mut self, batch: &mut Self::Batch) -> Result<(), DecodeError>;

    /// Samples the next token from the logits stored at slot `logit_idx` of the most
    /// recently decoded batch.  Returns `None` when the model signals end-of-sequence
    /// via an EOS token.
    fn sample_with_constraint(
        &mut self,
        logit_idx: usize,
        constraint: Option<&mut dyn SlmConstraint>,
    ) -> Result<Option<Self::Token>, SamplingError>;

    /// Converts `token` to its raw byte representation.
    ///
    /// - `buffer_size` – internal scratch buffer size; increase if tokens can produce
    ///   many bytes.
    /// - `special` – when `true`, special tokens (BOS, EOS, …) are rendered as their
    ///   text representation rather than being skipped.
    /// - `lstrip` – if `Some(n)`, strip up to `n` leading space bytes from the result.
    fn token_to_bytes(
        &self,
        token: Self::Token,
        special: bool,
        left_strip: Option<usize>,
    ) -> Result<Vec<u8>, TokenToStringError> {
        self.vocab().token_to_bytes(token, special, left_strip)
    }

    /// Tokenizes `str` into a sequence of model tokens.
    ///
    /// - `add_special` – prepend/append BOS/EOS markers as required by the model.
    /// - `parse_special` – treat special-token text representations (e.g. `<|im_start|>`)
    ///   as their corresponding token IDs rather than as plain text.
    fn str_to_tokens(
        &self,
        str: &str,
        add_special: bool,
        parse_special: bool,
    ) -> Result<Vec<Self::Token>, StringToTokenError> {
        self.vocab().str_to_tokens(str, add_special, parse_special)
    }

    /// Resets the context to an empty state, discarding the entire KV cache.
    fn clear(&mut self) -> Result<(), ContextError>;

    /// Discards all KV cache entries belonging to the sequence identified by
    /// `fork_id`, freeing the associated cache slots without affecting other
    /// sequences.  Equivalent to [`clear`](Self::clear) when only a single
    /// sequence is in use.
    fn drop(&mut self, fork_id: usize) -> Result<(), ContextError>;

    /// Removes all tokens that were added from the `pos`, effectively rolling the
    /// KV cache back to that position.  Returns the [`SlmPos`] at which the next
    /// token should be inserted.
    fn truncate(&mut self, pos: &SlmPos) -> Result<SlmPos, ContextError>;

    /// Removes the token range `[start_pos, end_pos)` from the middle of the KV
    /// cache, shifting subsequent tokens down.  `end_pos` is the position
    /// *immediately after* the last token to remove.  Returns the new tail
    /// [`SlmPos`] at which the next token should be inserted.
    fn cut(&mut self, start_pos: &SlmPos, end_pos: &SlmPos) -> Result<SlmPos, ContextError>;

    /// Serialises the full context state (KV cache, sampler state, etc.) to a byte
    /// buffer so it can be persisted or transferred.
    fn dump(&mut self) -> Result<Vec<u8>, ContextError>;

    /// Restores a context state previously produced by [`dump`](Self::dump).
    fn restore(&mut self, data: Vec<u8>) -> Result<(), ContextError>;

    /// Reports which in-place editing operations this context supports.
    ///
    /// The value is used by [`SlmSimpleInference`] to pick the cheapest rollback
    /// strategy.  See [`SlmEditLevel`] for the available levels.
    fn edit_level(&self) -> SlmEditLevel;
}
