pub mod context;
pub mod vocab;
pub mod model;
pub mod answer;
pub mod formatter;
pub mod inference;
pub mod simple_inference;
pub mod oracle;
pub mod hf_model;
pub mod errors;

mod llg_lark;
mod simple_vocab;
mod oracle_async;

pub use context::*;
pub use vocab::*;
pub use formatter::*;
pub use model::*;
pub use answer::*;
pub use inference::*;
pub use simple_inference::*;
pub use oracle::*;
pub use simple_vocab::*;
pub use hf_model::*;
pub use errors::*;
//pub use oracle_async::*;

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Pos {
    /// Zero-based index of the token slot within the sequence.
    pub token_pos: usize,
    /// Identifier of the parallel sequence this position belongs to.
    /// `0` is used for single-sequence (non-forked) inference.
    pub fork_id: usize,
}

#[allow(dead_code)]
impl Pos {
    fn fork_id(&self) -> usize {
        self.fork_id
    }
    fn token_pos(&self) -> usize {
        self.token_pos
    }
    pub fn new(token_pos: usize, fork_id: usize) -> Pos {
        Self { token_pos, fork_id }
    }
}

/// Identifies which participant in a conversation produced a given message.
///
/// Chat-template formatters use this to wrap messages in the correct
/// role-specific delimiters (e.g. `<|im_start|>user\n` for Qwen, `[INST]` for Mistral).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Role {
    /// A privileged initial message that sets the model's persona and constraints.
    System,
    /// A message from the human side of the conversation.
    User,
    /// A message generated by the model.
    Assistant,
}

impl Role {
    pub fn as_str(&self) -> &'static str {
        match self {
            Role::System => "system",
            Role::User => "user",
            Role::Assistant => "assistant",
        }
    }
}
