//! Core inference primitives for small language models.
//!
//! This module provides a model-agnostic abstraction layer for autoregressive
//! text generation, including:
//!
//! - [`Context`] and [`ContextBuilder`] for low-level KV-cache management
//! - [`Vocab`] for tokenization and vocabulary operations
//! - [`Formatter`] for model-specific chat templates
//! - [`Assistant`] for high-level conversational inference
//! - [`Inference`] trait for generation engines
//! - [`Constraint`] for structured output generation

pub mod answer;
pub mod assistant;
pub mod context;
pub mod errors;
pub mod formatter;
pub mod hf_model;
pub mod inference;
pub mod model;
pub mod simple_inference;
pub mod vocab;

mod async_assistant;
mod llg_lark;
mod simple_vocab;

pub use answer::*;
pub use assistant::*;
pub use context::*;
pub use errors::*;
pub use formatter::*;
pub use hf_model::*;
pub use inference::*;
pub use model::*;
pub use simple_inference::*;
pub use simple_vocab::*;
pub use vocab::*;
//pub use async_assistant::*;

/// Position in the KV cache identified by token index and fork ID.
///
/// Used to track locations within the cache for rollback operations
/// and multi-sequence (forked) inference.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Pos {
    /// Zero-based index of the token slot within the sequence.
    pub token_pos: usize,
    /// Identifier of the parallel sequence this position belongs to.
    /// `0` is used for single-sequence (non-forked) inference.
    pub fork_id: usize,
}

#[allow(dead_code)]
impl Pos {
    /// Create a new position with the given token index and fork ID.
    pub fn new(token_pos: usize, fork_id: usize) -> Pos {
        Self { token_pos, fork_id }
    }
    fn fork_id(&self) -> usize {
        self.fork_id
    }
    fn token_pos(&self) -> usize {
        self.token_pos
    }
}

/// Identifies which participant in a conversation produced a given message.
///
/// Chat-template formatters use this to wrap messages in the correct
/// role-specific delimiters (e.g. `<|im_start|>user\n` for Qwen, `[INST]` for Mistral).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Role {
    /// A privileged initial message that sets the model's persona and constraints.
    System,
    /// A message from the human side of the conversation.
    User,
    /// A message generated by the model.
    Assistant,
}

impl Role {
    /// Returns the string representation of this role.
    pub fn as_str(&self) -> &'static str {
        match self {
            Role::System => "system",
            Role::User => "user",
            Role::Assistant => "assistant",
        }
    }
}
