[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-L", "native=/usr/lib/x86_64-linux-gnu",
    "-C", "target-cpu=native",
    "-C", "link-arg=-Wl,--disable-new-dtags",
    "-C", "link-arg=-Wl,-rpath,$ORIGIN"
]

[env]
CUDAToolkit_ROOT="/usr/local/cuda"
CUDAARCHS = "native"
CUDACXX="/usr/local/cuda/bin/nvcc"
#CMAKE_BUILD_PARALLEL_LEVEL=8
